# Generated by Django 4.2.6 on 2023-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, default='main', max_length=100, null=True),
        ),
    ]
